### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by ackleyd1** [ackleyd1/codelab-advanced-css-selectors#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://ravedave.surge.sh/) and meets the following [project](http://lansingcodelab.com/lessons/advanced-css-selectors/1) criteria:
- [x] not have any classes or ids included anywhere in the HTML (we can do a lot without them!)
- [x] include a list where the background alternates every other item (hint: use the `:nth-child` selector)
- [x] include a visible change on list items when you hover over them with your mouse
- [x] include special, visible styles on only the first and last elements in the list
- [x] include at least one empty list item that your CSS will hide using the `:empty` selector
- [x] return no errors (warnings are OK) when the HTML document is uploaded to the [W3C Markup Validation Service](http://validator.w3.org/#validate_by_upload)
- [x] return no errors or warnings when contents of the CSS file are pasted into [CSS Lint](http://csslint.net/)

**Comment by ackleyd1** [comment]
Absolutely disgusting page but it meets the requirements. LGTM

**Comment by chrisvfritz** [comment]
Almost! It looks like a couple of these criteria still aren't met:
- include at least one empty list item that your CSS will hide using the :empty selector **(there is no empty list item being hidden with the `:empty` selector)**
- include special, visible styles on only the first and last elements in the list **(the last element has no special styles)**

Also, I've seen _way_ uglier pages than this. This is at least very readable and doesn't hurt my eyes. :smiley:

**Comment by ackleyd1** [comment]
Okay this should be fixed. There is an empty td that is hidden but since it still exists it threw off the red background order(2n+3). To fix this I targeted the last element and set it to red background.

**Comment by chrisvfritz** [comment]
Looks good! :shipit: :+1:
